# Regenerates ${STAMP_FILE} (build_info.h) with the project version and the
# build timestamp. Invoked by the svnsyncdrive stamp custom target before every
# build so the version/build labels always reflect the binary that was built.
if(NOT DEFINED STAMP_FILE OR NOT DEFINED VERSION_STRING)
    message(FATAL_ERROR
        "stamp-build.cmake needs -DSTAMP_FILE=<path> and -DVERSION_STRING=<version>")
endif()

string(TIMESTAMP BUILD_TIMESTAMP "%Y-%m-%d %H:%M:%S")

file(WRITE "${STAMP_FILE}"
    "// Generated by scripts/stamp-build.cmake before every build. Do not edit.\n"
    "#pragma once\n"
    "#define SVNSYNC_VERSION \"${VERSION_STRING}\"\n"
    "#define SVNSYNC_BUILD_TIMESTAMP \"${BUILD_TIMESTAMP}\"\n")

message(STATUS "Build stamp: SvnSyncDrive ${VERSION_STRING} ${BUILD_TIMESTAMP}")
